# Power Iteration
Another good resource: http://ergodic.ugr.es/cphys/LECCIONES/FORTRAN/power_method.pdf

In [1]:
import numpy as np

In [7]:
#transition_matrix
transition_matrix = np.array([[0, 0.5, 0, 0.5, 0],
                              [0, 0, 0.5, 0, 0.5],
                              [0, 0, 0, 1, 0],
                              [0, 0, 0, 0, 1],
                              [0.33333333, 0.33333333, 0.33333333, 0, 0]])

In [68]:
# Version 1
def eigenvalue(A, v):
    Av = A.dot(v)
    return v.dot(Av)

def power_iteration1(A, verbose=True):
    n, d = A.shape

    v = np.ones(d) / np.sqrt(d)
    ev = eigenvalue(A, v)
    count = 0
    
    while True:
        count += 1
        Av = A.dot(v)
        v_new = Av / np.linalg.norm(Av)

        ev_new = eigenvalue(A, v_new)
        
        if np.abs(ev - ev_new) < 0.00001:
            break
        
        v = v_new
        ev = ev_new
        if verbose:
            print(f'Step {count}:\n {v_new}')
    return ev_new, v_new, count

power_iteration1(np.transpose(transition_matrix), verbose=False)[1]

array([0.22153615, 0.3323206 , 0.38769688, 0.49849029, 0.66459259])

In [80]:
# Version 2
def power_iteration2(A, num_simulations,verbose=True):
    # Ideally choose a random vector
    # To decrease the chance that our vector
    # Is orthogonal to the eigenvector
    # b_k = np.array([1.0, 0, 0, 0, 0])
    b_k = np.random.rand(A.shape[1])

    for ix in range(num_simulations):
        # calculate the matrix-by-vector product Ab
        b_k1 = np.dot(np.transpose(A), b_k)

        # calculate the norm
        b_k1_norm = np.linalg.norm(b_k1)
        # re normalize the vector
        b_k = b_k1 / b_k1_norm
        if verbose:
            print(f'Step {ix}:\n {b_k}')
    return b_k

power_iteration2(transition_matrix, 24, verbose=True)

Step 0:
 [0.20136585 0.28930237 0.30661419 0.50717955 0.7242324 ]
Step 1:
 [0.2523576  0.357606   0.40356801 0.42576605 0.68138808]
Step 2:
 [0.22858194 0.3555677  0.40852845 0.53313474 0.6084355 ]
Step 3:
 [0.19649899 0.30723247 0.36874903 0.50654583 0.68879012]
Step 4:
 [0.23421511 0.33444092 0.39092138 0.47639234 0.67344143]
Step 5:
 [0.2252891  0.3428185  0.39311192 0.50985896 0.64593123]
Step 6:
 [0.21283661 0.32418693 0.38227646 0.4999456  0.67344081]
Step 7:
 [0.22601758 0.33316467 0.38922111 0.49204149 0.66657292]
Step 8:
 [0.2223141  0.33538551 0.38898875 0.50250821 0.65898881]
Step 9:
 [0.21889234 0.32965944 0.38599682 0.49839124 0.66784985]
Step 10:
 [0.22314562 0.33285186 0.38836702 0.4966203  0.66479697]
Step 11:
 [0.22157206 0.33313132 0.38797778 0.49987909 0.66296568]
Step 12:
 [0.22076542 0.33143959 0.38716289 0.49826019 0.66577182]
Step 13:
 [0.2221054  0.33257837 0.3879607  0.49795243 0.66452291]
Step 14:
 [0.22147667 0.33251384 0.3877426  0.49894363 0.66414875]
Step 

array([0.22153078, 0.33230934, 0.38769144, 0.49847943, 0.66461133])

In [79]:
# Version 3
def power_iteration3(xInit, tMatrix, nIter, verbose = True):
    state_vector = None
    for ix in range(nIter):    
        if verbose:
            print(f'Step {ix}:\n {tMatrix[0]}')
        tMatrix = tMatrix @ tMatrix #<-- preferred form of: tMatrix = tMatrix.dot(tMatrix)
    return tMatrix[0]

# note that the initial state will not affect the convergence states
xInit = np.array([1.0, 0, 0, 0, 0]) 
# xInit = np.random.rand(transition_matrix.shape[1])
# xInit = np.ones(transition_matrix.shape[1]) / np.sqrt(transition_matrix.shape[1])
# xInit = np.ones(transition_matrix.shape[1]) / (transition_matrix.shape[1])

power_iteration3(xInit, transition_matrix, 10, verbose=False)

array([0.10526282, 0.15789423, 0.18420993, 0.23684134, 0.31578845])

## Rayleigh quotient
The Rayleigh quotient is used in the min-max theorem to get exact values of all eigenvalues. It is also used in eigenvalue algorithms (such as Rayleigh quotient iteration) to obtain an eigenvalue approximation from an eigenvector approximation.
https://en.wikipedia.org/wiki/Rayleigh_quotient

In [29]:
# Using the Rayleigh quotient, the dominant eigenvalue is:
def rayeigh_q(A,x):
    return np.dot(A.dot(x),x)/np.dot(x,x)

In [48]:
eigen_V3 = power_iteration3(xInit, transition_matrix, 10, False)[0]
print(rayeigh_q(transition_matrix,eigen_V3))
print(eigenvalue(transition_matrix,eigen_V3))
print(eigen_V3)

# normalized
print(eigen_V3/sum(eigen_V3))

0.9999999968421052
0.22576031429932517
[0.10526282 0.15789423 0.18420993 0.23684134 0.31578845]
[0.10526316 0.15789474 0.18421053 0.23684211 0.31578947]


In [49]:
eigen_V2 = power_iteration2(transition_matrix, 100)
print(rayeigh_q(transition_matrix,eigen_V2))
print(eigenvalue(transition_matrix,eigen_V2))
print(eigen_V2)

# normalized
print(eigen_V2/sum(eigen_V2))

0.9999999968421052
0.9999999968421052
[0.22153951 0.33230926 0.38769414 0.4984639  0.66461853]
[0.10526316 0.15789474 0.18421053 0.23684211 0.31578947]


In [50]:
eigen_V1 = power_iteration1(np.transpose(transition_matrix))[1]
print(rayeigh_q(transition_matrix,eigen_V1))
print(eigenvalue(transition_matrix,eigen_V1))
print(eigen_V1)

# normalized
print(eigen_V1/sum(eigen_V1))

1.0000153271331802
1.00001532713318
[0.22153615 0.3323206  0.38769688 0.49849029 0.66459259]
[0.105261   0.15789928 0.18421085 0.23685339 0.31577547]
